version: '3.9'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: online_store
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data